### ISSUE TITLE
Documentation for injection?

### ISSUE THREAD

**Issue by FranklinChen** [snoyberg/file-embed#11]
I was mystified by the injection utilities in this package. Maybe there could be more documentation about what they are used for?

**Comment by snoyberg** [comment]
I'm definitely in favor of having docs, I just don't have time right now to
write them. Would you be able to take a shot at a PR for them? If you have
questions, I can answer them.

**Comment by snoyberg** [comment]
I've written some improved documentation and uploaded to Hackage. Please have a look at:

http://hackage.haskell.org/package/file-embed-0.0.8.2/docs/Data-FileEmbed.html#g:2
