### ISSUE TITLE
embedFile truncates files that contain certain multi-byte Unicode code points on older GHC versions

### ISSUE THREAD

**Issue by tdammers** [snoyberg/file-embed#12]
When I feed a file to embedFile that contains certain Unicode code points (in my case, one of them being the "sprocket" code point, "⚙"), the embedded bytestring ends up truncated on GHC 7.4; on GHC 7.6, everything works as expected. The offending code point is also mangled.

The following is a small example that reproduces the problem:

    {-#LANGUAGE TemplateHaskell #-}
    {-#LANGUAGE CPP #-}

    module Main where

    import qualified Data.ByteString.UTF8 as BS8
    import qualified Data.ByteString as BS
    import Data.Monoid
    import Data.FileEmbed

    main :: IO ()
    main = do
        putStrLn "***** Loaded at runtime with Data.ByteString.readFile: "
        loadStr >>= BS.putStr
        putStrLn "***** Embedded using Data.FileEmbed.embedFile: "
        BS.putStr embeddedStr

    embeddedStr :: BS.ByteString
    embeddedStr = $(embedFile __FILE__)

    loadStr :: IO BS.ByteString
    loadStr = BS.readFile __FILE__

    -- What follows is some comment to trigger the bug.
    -- ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙ ⚙
    -- If this line appears in full, then all is fine.

It *should* print its own source twice, but on my test system (32-bit debian stable, GHC 7.4.1), only the first one is correct, while the second prints a series of `â` and cuts off before printing the last line.

At a quick glance, I suspect that the use of `Data.ByteString.Char8.pack`/`unpack` is the culprit; I think I understand why it is being used here (limitations of older TH implementations), but apparently not all code points survive the round tripping. Maybe the bytestring could be constructed via a `[Word8]` literal instead?

**Comment by snoyberg** [comment]
It's been a while since I played with this, but I don't think that `[Word8]` was a realistic option, since it's representation was drastically larger than a `String` and could wipe out GHC's memory with tiny input. If you're interested in taking a swing at this, I'd be happy to review a PR.

**Comment by tdammers** [comment]
I've been playing with this a bit myself, and as you say, `[Word8]` is ridiculously slow and blows up GHC with trivial inputs. One thing I've tried is going through `show` on the TH side, and then `read` back into a ByteString at runtime, but obviously this lacks the `O(1)` construction that `unsafePackAddrLen` provides, so it's still pretty slow, albeit not as hard on memory size.

Which, as far as I can tell, means we can choose between a correct solution and an efficient one. There's a middle ground, which is to assume utf-8, and pack/unpack using functions from `utf8-string` rather than `Char8`.

This would maintain the efficiency of `unsafePackAddrLen`, and it would produce correct results for all utf8 input at least. It would still break on some binary files though (those that contain byte sequences that would be invalid when interpreted as utf-8), and it would introduce a dependency for the sole sake of supporting an old compiler release, so I don't think I like that solution a lot.

**Comment by snoyberg** [comment]
GHC 7.4 is not in enough circulation at this point to be worth significant changes for this, closing.
