### ISSUE TITLE
embedTextFile

### ISSUE THREAD

**Issue by phadej** [snoyberg/file-embed#13]
Could we add such function, I can make a PR?

```hs
import qualified Data.Text

myFile :: Data.Text.Text
myFile = $(embedTextFile "dirName/fileName")
```

**Comment by snoyberg** [comment]
I'd like to avoid adding an extra dependency, but I think if toy express
this in terms of fromString it will do what you want.

**Comment by phadej** [comment]
You mean to have

```hs
myStringFile :: FromString a => a
myStringFile = $(embedStringFile "dirName/fileName")
```

That will be ok with me, even better actually.

**Comment by snoyberg** [comment]
Yup, exactly. Then your `myFile` example will still work, but so will others like `String`, lazy `Text`, etc.

**Comment by snoyberg** [comment]
Thanks for PR, closing
