### ISSUE TITLE
Does embedding result in more memory usage?

### ISSUE THREAD

**Issue by cies** [snoyberg/file-embed#17]
When embedding a file it increases the binary size, obviously. But is it always loaded into memory? And can it get GC'd (I think this would be hard as I define it as top-level symbol)?

I tried figuring this out by simply embedding a big file, but it did not yield any obvious results... Measuring mem usage in Linux is not as straight forward as it might seem.

**Comment by snoyberg** [comment]
Afaik, the data is placed in the text portion of the binary, and is not affected at all by garbage collection.

**Comment by cies** [comment]
Thanks for elaborating. I'm closing this now.
