### ISSUE TITLE
Does `$(embedDir "someDir")` produce its result lazily?

### ISSUE THREAD

**Issue by seagreen** [snoyberg/file-embed#21]
There are various language-agnostic test suites for things like JSON floating around the internet containing lots of test `.json` files, and I often want to wrap them up into libraries. This could be a problem though if the test suite is very large. If I use `$(embedDir "someDir")` in my code, will the resulting list be produced lazily?

**Comment by snoyberg** [comment]
I'm not sure what "lazy" means in this case, because this is a function that will run at compile time. I think my answer is "doubly strict":

* At compile time, running something like `take 1 <$> embedDir "someDir"` will still force evaluation of the entire directory tree.
* At runtime, the list is fully evaluated even if you don't use it at all.

**Comment by seagreen** [comment]
> I'm not sure what "lazy" means in this case, because this is a function that will run at compile time. I think my answer is "doubly strict"

Ahahaha. That makes sense though.

If you're interested I'd be curious if there's a way to create a `Source (FilePath, ByteString) IO` using TH. Since that would require `conduit` as a dep though it's not really relevant to this lib, so feel free to close this.

**Comment by snoyberg** [comment]
What would be the intended semantics? Are you thinking it would perform the I/O at runtime or at compile time? It's certainly possible to make the function, the question is would it at all behave the way you expect. My guess is that it wouldn't.

**Comment by seagreen** [comment]
The intent would be to perform the I/O at runtime. Since I don't think I explained the situation well above: the goal is to take a bunch of test files and create a new `test-files-foo` library so those files can be conveniently used within the test suites of other haskell libraries. For small groups of test files, using `$(embedDir "someDir")` and then providing a `[(FilePath, ParsedFile)]` works awesome. For big groups of files where memory becomes a concern a nicer API would be to provide a `Source (FilePath, ParsedFile) IO`. Is that a better explanation of the situation?

Writing such a function is another matter, but happily I don't need it anytime soon, so I've got plenty of time to improve my TH knowledge before I do so=)

**Comment by snoyberg** [comment]
It doesn't sound like your use case involves performing any I/O at runtime. It sounds like you need to capture all of the test files at compile time and embed them in the library. A test question to see if this is correct: will the `someDir` be available in a known location when running the test suites for the other libraries?

**Comment by seagreen** [comment]
> It doesn't sound like your use case involves performing any I/O at runtime. It sounds like you need to capture all of the test files at compile time and embed them in the library.

Absolutely! Sorry even my improved explanation wasn't clear.

> A test question to see if this is correct: will the someDir be available in a known location when running the test suites for the other libraries?

Nope, I was thinking the only access to somedir at this point would be through `test-files-foo`'s API.

**Comment by snoyberg** [comment]
In that case, you have no option but to load the entire set of files into the executable, and providing access to them via a list is no worse than providing a conduit. Either way, the contents will be part of the executable itself and the `ByteString` will just have a pointer into the executable's memory space.

**Comment by seagreen** [comment]
That makes perfect sense now. I think if the test data gets to big I'll just provide a function to download it to `/tmp`. Thanks for bearing with my confusion about how this works, and feel free to close this.

**Comment by snoyberg** [comment]
No problem, glad it's clear now.
