### ISSUE TITLE
The docs on makeRelativeToProject seem to be broken

### ISSUE THREAD

**Issue by googleson78** [snoyberg/file-embed#31]
The haddock isn't showing up for some reason.

(`file-embed` version 0.0.11.1)

**Comment by snoyberg** [comment]
Interested in sending a PR?

**Comment by googleson78** [comment]
Hm, I mistakenly tagged the pr as closing this issue. There needs to be a new hackage upload first for the docs to update, right?

**Comment by snoyberg** [comment]
I've uploaded to Hackage in any event.

**Comment by googleson78** [comment]
Thanks!
