### ISSUE TITLE
Have dummySpace / inject / injectFile take an additional magic string

### ISSUE THREAD

**Issue by mgsloan** [snoyberg/file-embed#7]
It looks to me like an executable can only have one injected bytestring, because the magic string is always the same for `dummySpace`.

I can make a pull request adding this, if you want me to!

**Comment by snoyberg** [comment]
Would the PR add a new function that allows customizing the magic string?

**Comment by mgsloan** [comment]
Yes, but we'd need new versions of dummySpace / inject / injectFile.  Alternatively, it might be reasonable to break the API, in order to encourage users to provide a magic string (so that different uses of this injection don't interfere with eachother).  While API changes should be avoided, are there many users of this?  I see file-embed has lots of reverse dependencies, but I figure most of them are using the normal file embedding stuff.  http://packdeps.haskellers.com/reverse/file-embed

**Comment by snoyberg** [comment]
Then we need new versions of those three functions. Not breaking API on a whim.

**Comment by gregwebs** [comment]
does anyone have some example usage of the injection stuff? I am not sure how to use it. My use case is I want to use embed-file but not invoke Template Haskell.

**Comment by mgsloan** [comment]
@gregwebs, I've been using this as a reference for the injection stuff: http://www.yesodweb.com/blog/2011/06/building-better-chm

It would probably good to add more haddocks to this module, as well.  You ought to be able to use injection without TH, but I'm not sure how to write a `StringPrimL` in code.  Something like this might work, though (untested):

```
{-# LANGAUGE OverloadedStrings #-}

import qualified Data.ByteString as BS

-- magic string ++ padded size ++ payload space
-- "feMS" ++ (replicate 19 '0' ++ "4") ++ replicate 4 '0'
bs :: BS.ByteString
bs = "feMS000000000000000000040000"

injected :: BS.ByteString
injected = BS.drop 24 bs
```

Then, use `injectFile` on the compiled binary to inject your own `ByteString` (up to 4 bytes).

**Comment by gregwebs** [comment]
I don't see how we can efficiently reserve the dummy space without `StringPrimL` from template-haskell. Perhaps it is possible with some pointer tricks.

**Comment by snoyberg** [comment]
@gregwebs I just updated the documentation:

http://hackage.haskell.org/package/file-embed-0.0.8.2/docs/Data-FileEmbed.html#g:2

Closing this issue, as the original topic has been addressed. Greg: if you have questions about how to use it, let's follow up in the mailing list or a different issue.
