### ISSUE TITLE
Is the summary accurate?

### ISSUE THREAD

**Issue by seagreen** [snoyberg/file-embed#9]
The summary is:

"Use Template Haskell to read a file or all the files in a directory, and turn them into (path, text) pairs embedded in your haskell code."

But it seems like "(path, bytestring)" would be more accurate than "(path, text)". It's almost too small of a thing to bring up, but I thought it was worthwhile since it's the first thing people see on Hackage.

**Comment by snoyberg** [comment]
You're correct. Could you send a PR to update it?

**Comment by seagreen** [comment]
Of course! I also deleted the old `README` file (not `README.md`). If that's not OK let me know.

 https://github.com/snoyberg/file-embed/pull/10

**Comment by snoyberg** [comment]
No, that's great, thanks!
